/*
 * This file is generated by jOOQ.
 */
package com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.PsstoregamessAuditLog;


/**
 * This class is generated by jOOQ.
 */

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PsstoregamessAuditLogRecord extends UpdatableRecordImpl<PsstoregamessAuditLogRecord> implements Record7<String, Integer, Byte, String, String, String, String> {

    private static final long serialVersionUID = 1313807308;

    /**
     * Setter for <code>games.psstoregamess_audit_log.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.revtype</code>.
     */
    public void setRevtype(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.revtype</code>.
     */
    public Byte getRevtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.device</code>.
     */
    public void setDevice(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.device</code>.
     */
    public String getDevice() {
        return (String) get(3);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.price</code>.
     */
    public void setPrice(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.price</code>.
     */
    public String getPrice() {
        return (String) get(5);
    }

    /**
     * Setter for <code>games.psstoregamess_audit_log.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>games.psstoregamess_audit_log.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, Byte, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, Byte, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REV;
    }

    @Override
    public Field<Byte> field3() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REVTYPE;
    }

    @Override
    public Field<String> field4() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.DEVICE;
    }

    @Override
    public Field<String> field5() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.NAME;
    }

    @Override
    public Field<String> field6() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.PRICE;
    }

    @Override
    public Field<String> field7() {
        return PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.TYPE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRev();
    }

    @Override
    public Byte component3() {
        return getRevtype();
    }

    @Override
    public String component4() {
        return getDevice();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getPrice();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRev();
    }

    @Override
    public Byte value3() {
        return getRevtype();
    }

    @Override
    public String value4() {
        return getDevice();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getPrice();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public PsstoregamessAuditLogRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value2(Integer value) {
        setRev(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value3(Byte value) {
        setRevtype(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value4(String value) {
        setDevice(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value6(String value) {
        setPrice(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public PsstoregamessAuditLogRecord values(String value1, Integer value2, Byte value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PsstoregamessAuditLogRecord
     */
    public PsstoregamessAuditLogRecord() {
        super(PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG);
    }

    /**
     * Create a detached, initialised PsstoregamessAuditLogRecord
     */
    public PsstoregamessAuditLogRecord(String id, Integer rev, Byte revtype, String device, String name, String price, String type) {
        super(PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG);

        set(0, id);
        set(1, rev);
        set(2, revtype);
        set(3, device);
        set(4, name);
        set(5, price);
        set(6, type);
    }
}
