/*
 * This file is generated by jOOQ.
 */
package com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Revinfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevinfoRecord extends UpdatableRecordImpl<RevinfoRecord> implements Record2<Integer, Long> {

    private static final long serialVersionUID = -94715254;

    /**
     * Setter for <code>games.revinfo.rev</code>.
     */
    public void setRev(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>games.revinfo.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>games.revinfo.revtstmp</code>.
     */
    public void setRevtstmp(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>games.revinfo.revtstmp</code>.
     */
    public Long getRevtstmp() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Revinfo.REVINFO.REV;
    }

    @Override
    public Field<Long> field2() {
        return Revinfo.REVINFO.REVTSTMP;
    }

    @Override
    public Integer component1() {
        return getRev();
    }

    @Override
    public Long component2() {
        return getRevtstmp();
    }

    @Override
    public Integer value1() {
        return getRev();
    }

    @Override
    public Long value2() {
        return getRevtstmp();
    }

    @Override
    public RevinfoRecord value1(Integer value) {
        setRev(value);
        return this;
    }

    @Override
    public RevinfoRecord value2(Long value) {
        setRevtstmp(value);
        return this;
    }

    @Override
    public RevinfoRecord values(Integer value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevinfoRecord
     */
    public RevinfoRecord() {
        super(Revinfo.REVINFO);
    }

    /**
     * Create a detached, initialised RevinfoRecord
     */
    public RevinfoRecord(Integer rev, Long revtstmp) {
        super(Revinfo.REVINFO);

        set(0, rev);
        set(1, revtstmp);
    }
}
