/*
 * This file is generated by jOOQ.
 */
package com.mrdave19.PSStoreGameScraperV3.entity.jooq.games;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Psstoregamess;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.PsstoregamessAuditLog;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Revinfo;


/**
 * A class modelling indexes of tables of the <code>games</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------


    public static final Index PSSTOREGAMESS_PRIMARY = Indexes0.PSSTOREGAMESS_PRIMARY;
    public static final Index PSSTOREGAMESS_AUDIT_LOG_FKPVIOTTRK2Y8L5FLUHAA9NDDOX = Indexes0.PSSTOREGAMESS_AUDIT_LOG_FKPVIOTTRK2Y8L5FLUHAA9NDDOX;
    public static final Index PSSTOREGAMESS_AUDIT_LOG_PRIMARY = Indexes0.PSSTOREGAMESS_AUDIT_LOG_PRIMARY;
    public static final Index REVINFO_PRIMARY = Indexes0.REVINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PSSTOREGAMESS_PRIMARY = Internal.createIndex("PRIMARY", Psstoregamess.PSSTOREGAMESS, new OrderField[] { Psstoregamess.PSSTOREGAMESS.ID }, true);
        public static Index PSSTOREGAMESS_AUDIT_LOG_FKPVIOTTRK2Y8L5FLUHAA9NDDOX = Internal.createIndex("FKpviottrk2y8l5fluhaa9nddox", PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG, new OrderField[] { PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REV }, false);
        public static Index PSSTOREGAMESS_AUDIT_LOG_PRIMARY = Internal.createIndex("PRIMARY", PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG, new OrderField[] { PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.ID, PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REV }, true);
        public static Index REVINFO_PRIMARY = Internal.createIndex("PRIMARY", Revinfo.REVINFO, new OrderField[] { Revinfo.REVINFO.REV }, true);
    }
}
