/*
 * This file is generated by jOOQ.
 */
package com.mrdave19.PSStoreGameScraperV3.entity.jooq.games;


import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Psstoregamess;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.PsstoregamessAuditLog;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Revinfo;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.records.PsstoregamessAuditLogRecord;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.records.PsstoregamessRecord;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.records.RevinfoRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>games</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RevinfoRecord, Integer> IDENTITY_REVINFO = Identities0.IDENTITY_REVINFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PsstoregamessRecord> KEY_PSSTOREGAMESS_PRIMARY = UniqueKeys0.KEY_PSSTOREGAMESS_PRIMARY;
    public static final UniqueKey<PsstoregamessAuditLogRecord> KEY_PSSTOREGAMESS_AUDIT_LOG_PRIMARY = UniqueKeys0.KEY_PSSTOREGAMESS_AUDIT_LOG_PRIMARY;
    public static final UniqueKey<RevinfoRecord> KEY_REVINFO_PRIMARY = UniqueKeys0.KEY_REVINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PsstoregamessAuditLogRecord, RevinfoRecord> FKPVIOTTRK2Y8L5FLUHAA9NDDOX = ForeignKeys0.FKPVIOTTRK2Y8L5FLUHAA9NDDOX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RevinfoRecord, Integer> IDENTITY_REVINFO = Internal.createIdentity(Revinfo.REVINFO, Revinfo.REVINFO.REV);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PsstoregamessRecord> KEY_PSSTOREGAMESS_PRIMARY = Internal.createUniqueKey(Psstoregamess.PSSTOREGAMESS, "KEY_psstoregamess_PRIMARY", Psstoregamess.PSSTOREGAMESS.ID);
        public static final UniqueKey<PsstoregamessAuditLogRecord> KEY_PSSTOREGAMESS_AUDIT_LOG_PRIMARY = Internal.createUniqueKey(PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG, "KEY_psstoregamess_audit_log_PRIMARY", PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.ID, PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REV);
        public static final UniqueKey<RevinfoRecord> KEY_REVINFO_PRIMARY = Internal.createUniqueKey(Revinfo.REVINFO, "KEY_revinfo_PRIMARY", Revinfo.REVINFO.REV);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PsstoregamessAuditLogRecord, RevinfoRecord> FKPVIOTTRK2Y8L5FLUHAA9NDDOX = Internal.createForeignKey(com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.Keys.KEY_REVINFO_PRIMARY, PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG, "FKpviottrk2y8l5fluhaa9nddox", PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG.REV);
    }
}
