/*
 * This file is generated by jOOQ.
 */
package com.mrdave19.PSStoreGameScraperV3.entity.jooq.games;


import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Psstoregamess;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.PsstoregamessAuditLog;
import com.mrdave19.PSStoreGameScraperV3.entity.jooq.games.tables.Revinfo;


/**
 * Convenience access to all tables in games
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    

    /**
     * The table <code>games.psstoregamess</code>.
     */
    public static final Psstoregamess PSSTOREGAMESS = Psstoregamess.PSSTOREGAMESS;

    /**
     * The table <code>games.psstoregamess_audit_log</code>.
     */
    public static final PsstoregamessAuditLog PSSTOREGAMESS_AUDIT_LOG = PsstoregamessAuditLog.PSSTOREGAMESS_AUDIT_LOG;

   

    /**
     * The table <code>games.revinfo</code>.
     */
    public static final Revinfo REVINFO = Revinfo.REVINFO;
}
